default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  adapter: <%= ENV.fetch("ANYCABLE_ENABLED", "true") == "true" ? "any_cable" : "redis" %>
  <% if ENV.fetch("ANYCABLE_ENABLED", "true") != "true" %>
  url: redis://localhost:6379
  channel_prefix: campfire_development
  <% end %>

test:
  adapter: test

performance:
  adapter: <%= ENV.fetch("CABLE_ADAPTER", "redis") %>
  url: redis://localhost:6379
  channel_prefix: campfire_performance

production:
  adapter: <%= ENV.fetch("ANYCABLE_ENABLED", "true") == "true" ? "any_cable" : "redis" %>
  <% if ENV.fetch("ANYCABLE_ENABLED", "true") != "true" %>
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>
  channel_prefix: campfire_production
  <% end %>
