default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  adapter: <%= ENV.fetch("ANYCABLE_ENABLED", "true") == "true" ? "any_cable" : "redis" %>

test:
  adapter: test

performance:
  adapter: <%= ENV.fetch("CABLE_ADAPTER", "redis") %>
  url: redis://localhost:6379
  channel_prefix: campfire_performance

production:
  adapter: <%= ENV.fetch("ANYCABLE_ENABLED", "true") == "true" ? "any_cable" : "redis" %>
