default: &default
  adapter: redis
  url: redis://localhost:6379

development:
  adapter: <%= ENV["ANYCABLE_ENABLED"] == "false" ? "redis" : "any_cable" %>
  <% if ENV["ANYCABLE_ENABLED"] == "false" %>
  url: redis://localhost:6379
  channel_prefix: campfire_development
  <% end %>

test:
  adapter: test

performance:
  adapter: <%= ENV.fetch("CABLE_ADAPTER", "redis") %>
  url: redis://localhost:6379
  channel_prefix: campfire_performance

production:
  adapter: <%= ENV["ANYCABLE_ENABLED"] == "false" ? "redis" : "any_cable" %>
  <% if ENV["ANYCABLE_ENABLED"] == "false" %>
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379") %>
  channel_prefix: campfire_production
  <% end %>
